spring.application.name=kishan_setu_backend

spring.mongodb.uri=${MONGO_URI}

cloudinary.cloud_name=${CLOUD_NAME}
cloudinary.api_key=${API_KEY}
cloudinary.api_secret=${API_SECRET}

gemini.api.key=${GEMINI_API}
gemini.api.url=${GEMINI_API_URL}

